<template>
  <div>
    <SectionsIntro/>
    <div>
      <SectionsFeatureOfProducts/>
      <SectionsService/>
      <SectionsUsefulFeatures/>
      <SectionsCoreFeatures/>
    </div>
    <SectionsFunctions/>
    <div>
      <SectionsPricing/>
      <SectionsTeamMembers/>
      <SectionsTestimonials/>
      <SectionsOurBlog/>
      <SectionsSubscribeBlog/>
      <SectionsBlogs/>
    </div>
  </div>
</template>
